 <td></td>
 </tr>
 <tr><td colspan="15">Bonus&nbsp;stage:&nbsp;<input type="checkbox" name="BonusStage" Value="True" <%Checked%>></td></tr>
 <tr><td colspan="15">Player&nbsp;count&nbsp;scale:&nbsp;<input class=textbox type="text" name="PlayerCountScale" Value="<%PlayerCountScale%>" size="3" maxlength="5"</td></tr>
 <tr>
  <td colspan="15">
   <nobr>
   <input class="button" type="Submit" name="Update" Value="Update">
   <input class="button" type="Submit" name="Delete" Value="Delete">
   </nobr>
  </td>
 </tr>
</form>

