  <tr>
   <td colspan="15">
    <nobr>
    <input class="button" type="Submit" name="Update" Value="Update" onClick="setSubmitAction(this.name);">
    <input style="<%HideMoveUpButtton%>" class="button" type="Submit" name="MoveUp" Value="Move Up" onClick="setSubmitAction(this.name);">
    <input style="<%HideDeleteButtton%>" class="button" type="Submit" name="Delete" Value="Delete" onClick="setSubmitAction(this.name);">
    </nobr>
   </td>
  </tr>
 </form>

