   <td width="1"><input class="textbox" type="text" name="MonsterNum0" value="<%MonsterNum0%>" size="1" maxlength="2"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterName0" value="<%MonsterName0%>" size="20" maxlength="48"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterNum1" value="<%MonsterNum1%>" size="1" maxlength="2"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterName1" value="<%MonsterName1%>" size="20" maxlength="48"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterNum2" value="<%MonsterNum2%>" size="1" maxlength="2"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterName2" value="<%MonsterName2%>" size="20" maxlength="48"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterNum3" value="<%MonsterNum3%>" size="1" maxlength="2"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterName3" value="<%MonsterName3%>" size="20" maxlength="48"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterNum4" value="<%MonsterNum4%>" size="1" maxlength="2"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterName4" value="<%MonsterName4%>" size="20" maxlength="48"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterNum5" value="<%MonsterNum5%>" size="1" maxlength="2"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterName5" value="<%MonsterName5%>" size="20" maxlength="48"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterNum6" value="<%MonsterNum6%>" size="1" maxlength="2"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterName6" value="<%MonsterName6%>" size="20" maxlength="48"></td>

