   <td width="1"><input class="textbox" type="text" name="MonsterAlias" value="<%MonsterAlias%>" size="20" maxlength="48"<%readonly%>></td>
   <td width="1"><input class="textbox" type="text" name="MonsterClass" value="<%MonsterClass%>" size="48" maxlength="64"<%readonly%>></td>
   <td width="1"><input class="textbox" type="text" name="HeadHealthScale" value="<%HeadHealthScale%>" size="6" maxlength="6"></td>
   <td width="1"><input class="textbox" type="text" name="HealthScale" value="<%HealthScale%>" size="6" maxlength="6"></td>
   <td width="1"><input class="textbox" type="text" name="SpeedScale" value="<%SpeedScale%>" size="6" maxlength="6"></td>
   <td width="1"><input class="textbox" type="text" name="DamageScale" value="<%DamageScale%>" size="6" maxlength="6"></td>
   <td width="1"><input class="textbox" type="text" name="MotionDetectorThreat" value="<%MotionDetectorThreat%>" size="6" maxlength="6"></td>

