  <tr>
   <td width="1"><input class="textbox" type="text" name="MonsterNum0_<%RowIndex%>" value="<%MonsterNum0%>" size="1" maxlength="2"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterName0_<%RowIndex%>" value="<%MonsterName0%>" size="20" maxlength="48"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterNum1_<%RowIndex%>" value="<%MonsterNum1%>" size="1" maxlength="2"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterName1_<%RowIndex%>" value="<%MonsterName1%>" size="20" maxlength="48"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterNum2_<%RowIndex%>" value="<%MonsterNum2%>" size="1" maxlength="2"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterName2_<%RowIndex%>" value="<%MonsterName2%>" size="20" maxlength="48"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterNum3_<%RowIndex%>" value="<%MonsterNum3%>" size="1" maxlength="2"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterName3_<%RowIndex%>" value="<%MonsterName3%>" size="20" maxlength="48"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterNum4_<%RowIndex%>" value="<%MonsterNum4%>" size="1" maxlength="2"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterName4_<%RowIndex%>" value="<%MonsterName4%>" size="20" maxlength="48"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterNum5_<%RowIndex%>" value="<%MonsterNum5%>" size="1" maxlength="2"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterName5_<%RowIndex%>" value="<%MonsterName5%>" size="20" maxlength="48"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterNum6_<%RowIndex%>" value="<%MonsterNum6%>" size="1" maxlength="2"></td>
   <td width="1"><input class="textbox" type="text" name="MonsterName6_<%RowIndex%>" value="<%MonsterName6%>" size="20" maxlength="48"></td>
  </tr>

